### ISSUE TITLE
pybluez ble support (gattlib missing)

### ISSUE THREAD

**Issue by JorgePe** [ev3dev/pybluez#1]
Hi!
I'm using snapshot image "snapshot-ev3dev-jessie-ev3-generic-2016-11-07.img.xz",
4.4.24-16-ev3dev-ev3
fresh installation, nothing else installed or even updated

For proper use of pybluez with BLE devices gattlib (pygattlib) is required.
I installed the proper dependencies for gattlib and then tried the instructions in this repo README but failed:
`Directory '.' is not installable. File 'setup.py' not found.`

I can add gattlib like I did in the past for the WeDo 2.0 tutorial (compilling from source) but it takes a lot of time and I think it still requires an huge swapfile.

Am I missing something?
Is it possible to include gattlib in future snapshots?

**Comment by dlech** [comment]
It looks like pygattlib is a separate package from this one. Please open an issue in the main ev3dev issues. https://github.com/ev3dev/ev3dev/issues
